adapter = "cloud"
# serial_port = "/dev/ACM0"
baudrate = 1000000
mqtt_host = "argus.paris.inria.fr"
mqtt_port = 8883
mqtt_use_tls = true
# swarmit_network_id = "1200" # Equivalent to 0x1200
devices = ""
# verbose = false
